level = [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"            W            WW             ",
"            W             W     WWWWWW  ",
"         WWWW   WWW   W              WWW",
"            W     W   W                 ",
"            W     W   WWWWWW   WWW      ",
"                  W       WW   W     WWW",
"     W            W       WW   W     W  ",
"     WW   WWW     WWWWWW  WW   W     W  ",
"            W                  WWW   W  ",
"WWW                            WWW   W  ",
"      WWWWWW     WWW                 W  ",
"      W          W         WW        W  ",
"      W          W         WW     WWWW  ",
"      WWW      WWW              WW      ",
"                     WWW        WW      ",
"WWW                    W         WWW    ",
"  WWWWWWW      W       WWW       WWW    ",
"        W    WWW                        ",
"        W    W                          ",
"     WWWW    W    W    WWWW    W     W  ",
"             WWWWWW       W    W     W  ",
"  W              WW       WWWWWW    WW  ",
"  WW                  W       W     W   ",
"   W   WW   WW        W             W   ",
"        W             W                 ",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]
