level = [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"  W         W            WW             ",
"  W         W             W     WWWWW   ",
"  WWWW   WWWW   WWW   W             WWWW",
"            W     W   W                 ",
"            W     W   WWWWWW   WWW      ",
"  WWWW            W        W   W     WWW",
"     W            W        W   W     W  ",
"     WW   WWW     WWWWWW   W   W     W  ",
"            W                  WWW   W  ",
"WWW         W                  WWW   W  ",
"      WWWWWWW    WWW       W         W  ",
"      W          W         W         W  ",
"      W          W     wwwwWWW   WWWWW  ",
"      WWW      WWW               W      ",
"                     WWW         W      ",
"WWW                    W     WWWWW      ",
"  WWWWWWW      WWW     WWW       WWWW   ",
"        W    WWW                   W    ",
"        W    W                     W    ",
"  W   WWW    W         WWWW    W        ",
"  W          WWWWWW       W    W        ",
"  W               W       WWWWWW    WW  ",
"  WWWWWWW         WWWWW       W     W   ",
"                      W             W   ",
"                      W                 ",
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]
